# The URL the site will be built for
base_url = "https://chaoskollektiv.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[search]
include_title = true
include_description = false
include_path = false
include_content = true
index_format = "elasticlunr_javascript"

[extra]
# Put all your custom variables here
search_paths = ["content/projects"]
